JAGUARETE/urls.py
from django.urls import path
from . import views

app_name = "JAGUARETE"

urlpatterns = [
    path('', views.index, name="index"),
    path('acerca-de/', views.acerca_de, name="acerca-de"),
    path('contacto/', views.contacto, name="contacto"),
    path('nuevo_producto', views.nuevo_producto, name="nuevo_producto"),
    path('editar_producto/<int:id_producto>', views.editar_producto, name="editar_producto"),
    path('producto/<int:id_producto>', views.producto, name="producto")
]

proyecto_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('JAGUARETE.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

JAGUARETE/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Categoria(models.Model):
    categoria = models.CharField(max_length=64)
    descripcion = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.categoria} - {self.descripcion}"

class Producto(models.Model):
    titulo = models.CharField(max_length=64)
    imagen = models.FileField(upload_to="imagenes/")
    descripcion = models.CharField(max_length=255)
    precio = models.FloatField(max_length=6)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, related_name="categoria_producto")

    def __str__(self):
        return f"Producto {self.titulo} - {self.categoria}"

class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuario')
    productos = models.ManyToManyField(Producto, blank=True, related_name="productos")
    total = models.FloatField(max_length=6)

    def __str__(self):
        return f"El usuario {self.usuario} adquirio los productos: {self.productos} con un precio de {self.total}"

JAGUARETE/forms.py
from django import forms
from .models import Producto

class FormProducto(forms.ModelForm):
    
    #campos del modelo
    class Meta:
       model = Producto
       fields = ('titulo', 'imagen', 'descripcion', 'precio', 'categoria')

proyecto_final/JAGUARETE/forms.py
from django import forms
from .models import Producto

class FormProducto(forms.ModelForm):
    
    #campos del modelo
    class Meta:
       model = Producto
       fields = ('titulo', 'imagen', 'descripcion', 'precio', 'categoria')

JAGUARETE/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Producto, Categoria
from .forms import *
from django.shortcuts import redirect, get_object_or_404

# Create your views here.
def index(request):
    return render(request, "tienda/index.html",{
        "productos": Producto.objects.all(),
        "categorias": Categoria.objects.all()
    })

def acerca_de(request):
    return render(request, "tienda/acerca-de.html",{
        "categorias": Categoria.objects.all()
    })

def contacto(request):
    return render(request, "tienda/contacto.html",{
        "categorias": Categoria.objects.all()
    })

def nuevo_producto(request):
    if request.method == 'POST':
        form = FormProducto(request.POST, request.FILES, instance=Producto(imagen = request.FILES['imagen']))
        if form.is_valid():
            form.save()
            return redirect("JAGUARETE:index")
    else:
        return render(request, "tienda/nuevo_producto.html",{
        "categorias": Categoria.objects.all()
        })

def editar_producto(request, id_producto):
    producto = get_object_or_404(Producto, id=id_producto)
    if request.method == "POST":
        form = FormProducto(data = request.POST, files = request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect("JAGUARETE:index")
    else:
        form = FormProducto(instance=producto)
        return render(request, 'tienda/editar_producto.html',{
            "producto": producto,
            "categorias": Categoria.objects.all(),
            "form": form
        }) 

def producto(request, id_producto):
    producto = get_object_or_404(Producto, id=id_producto)
    return render(request, 'tienda/producto.html',{
        "producto": producto
    })

JAGUARETE/templates/tienda/acerca-de.html
{% extends "tienda/layout.html" %}
{% block body %}
<h1>Acerca de</h1>
{% endblock %}

JAGUARETE/templates/tienda/contacto.html
{% extends "tienda/layout.html" %}
{% block body %}
<h1>Contacto</h1>
{% endblock %}

JAGUARETE/templates/tienda/editar_producto.html
{% extends "tienda/layout.html" %}
{% block body %}
<h1>Producto</h1>
<form action="{% url 'JAGUARETE:editar_producto' producto.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-12">
            <label for="titulo">Titulo</label>
            <input type="text" class="form-control" id="titulo" name="titulo" value="{{producto.titulo}}">
        </div>
        <div class="form-group col-md-6 col-sm-12">
            <label for="imagen">Imagen</label>
            <input type="file" class="form-control" id="imagen" name="imagen">
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="categoria">Categoria</label>
                <select name="categoria" id="categoria" class="form-control">
                    {% for categoria in categorias %}
                    <option value="{{ categoria.id }}">{{categoria.categoria}}</option>
                    {%endfor%}
                </select>
            </div>
            <div class="form-group">
                <label for="descripcion">Descripcion</label>
                <textarea name="descripcion" id="descripcion" class="form-control" rows="5">{{ producto.descripcion}}</textarea>
            </div>
            <div class="form-group">
                <label for="precio">Precio</label>
                <input type="text" class="form-control" name="precio" id="precio" value="{{producto.precio}}">
            </div>
            <a href="#" class="btn btn-danger float-right">Eliminar</a>
            <button type="submit" class="btn btn-warning float-right">Editar</button>
        </div>
    </div>
</form>
{% endblock %}

JAGUARETE/templates/tienda/index.html
{% extends "tienda/layout.html" %} {% block body %}
<h1 style="margin-top: 3rem">Ultimos productos</h1>
<div class="row" style="margin-top: 2rem">
  {% for producto in productos %}
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="card" style="width: 18rem">
      <img src="{{ media_url}}{{producto.imagen.url}}" class="card-img-top" alt="producto.imagen.name" />
      <div class="card-body">
        <h5 class="card-title">{{ producto.titulo }}</h5>
        <p class="card-text">
          {{producto.descripcion}}
        </p>
        {% if perms.producto.change_producto %}
        <a href="{% url 'JAGUARETE:editar_producto' producto.id %}" class="btn btn-warning">Editar</a>
        {% else %}
        <a href="{% url 'JAGUARETE:producto' producto.id %}" class="btn btn-primary">Ver...</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<div class="row">
  <div class="card col-12" style="margin-top: 5rem">
    <div class="car-header bg-dark text-white">
        <h1 class="text-center">Más productos</h1>
    </div>
    <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">An item <a href="#" class="btn btn-primary float-right">Ver producto</a></li>
          <li class="list-group-item">A second item</li>
          <li class="list-group-item">A third item</li>
        </ul>
    </div>
  </div>
</div>

{% endblock %}

JAGUARETE/templates/tienda/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KUAGURETE KAA S.A.</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">KAGUARETE KAA S.A.</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse clearfix" id="navbarText">
              <ul class="navbar-nav mr-auto float-right">
                {% if user.is_authenticated %}
                Bienvenido {{user.get_username}} 
                <li class="nav-item">
                  <a class="nav-link btn btn-danger text-white ," href="{% url 'logout' %}">Salir</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link btn btn-dark text-white" href="{% url 'login' %}">LOGIN</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">REGISTRO</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="#">CARRITO</a>
                </li>
              </ul>
            </div>
          </nav>
    </header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'JAGUARETE:index' %}">HOME</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                CATEGORIAS
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for categoria in categorias %}
                <a class="dropdown-item" href="#">{{categoria.categoria}}</a>
                {%endfor%}
              </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'JAGUARETE:acerca-de' %}">ACERCA DE</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'JAGUARETE:contacto' %}">CONTACTO</a>
            </li>
            {% if perms.producto.new_producto %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'JAGUARETE:nuevo_producto' %}">NUEVO PRODUCTO</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Buscar..." aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Buscar</button>
          </form>
        </div>
      </nav>
      <div class="container">
          {% block body %}
          {% endblock %}
      </div>
      <style>
        .footer{
          color: white;
          text-align: center;
          margin-top:3rem;
          padding: 2rem;
        }
      </style>
      <footer class="bg-dark footer">
        Desarrolldo por AMB - Derechos reservados 2021
      </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
</body>
</html>

JAGUARETE/templates/tienda/nuevo_producto.html
{% extends "tienda/layout.html" %}
{% block body %}
<h1>Nuevo producto</h1>
<form action="{% url 'JAGUARETE:nuevo_producto' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-12">
            <label for="titulo">Titulo</label>
            <input type="text" class="form-control" id="titulo" name="titulo" placeholder="Ingrese el título del producto">
        </div>
        <div class="form-group col-md-6 col-sm-12">
            <label for="imagen">Imagen</label>
            <input type="file" class="form-control" id="imagen" name="imagen">
        </div>
        <div class="col-md-6 col-sm-12">
            <div class="form-group">
                <label for="categoria">Categoria</label>
                <select name="categoria" id="categoria" class="form-control">
                    {% for categoria in categorias %}
                    <option value="{{ categoria.id }}">{{categoria.categoria}}</option>
                    {%endfor%}
                </select>
            </div>
            <div class="form-group">
                <label for="descripcion">Descripcion</label>
                <textarea name="descripcion" id="descripcion" class="form-control" rows="5" placeholder="Ingrese la descripción del producto"></textarea>
            </div>
            <div class="form-group">
                <label for="precio">Precio</label>
                <input type="text" class="form-control" name="precio" id="precio" placeholder="Ingrese precio">
            </div>
            <button type="submit" class="btn btn-primary float-right">Crear</button>
        </div>
    </div>
</form>
{% endblock %}

JAGUARETE/templates/tienda/producto.html
{% extends "tienda/layout.html" %}
{% block body %}
<div class="card">
    <div class="card-header">
        <h1 class="text-center">{{producto.titulo}}</h1>
    </div>
    .<div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <img src="{{media_url}}{{producto.imagen.url}}" alt="" class="img-fluid">
            </div>
            <div class="col-md-6">
                <h2>Categoria: {{producto.categoria.categoria}}</h2>
                <h3>Descripción: </h3>
                <p>{{producto.descripcion}}</p>
                <h3>Precio: {{producto.precio}}</h3>
                <a href="#" class="btn btn-info">Agregar al carrito</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}